defmodule ScreenWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :screen

  # The session will be stored in the cookie, signed and encrypted.
  @session_options [
    store: :cookie,
    key: "_screen_key",
    signing_salt: "+Rl4Ylbq",
    encryption_salt: "k3Fz8mNp",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # The SPA is a static page without access to the session CSRF token,
  # so we disable check_csrf for the user socket and rely on check_origin instead.
  socket "/socket", ScreenWeb.UserSocket,
    websocket: [connect_info: [session: @session_options], check_csrf: false, check_origin: :conn]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :screen,
    gzip: not code_reloading?,
    only: ScreenWeb.static_paths(),
    only_matching: ~w(workbox-),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :screen
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ScreenWeb.Router
end
